[package]
name = "indradb-wikipedia"
version = "0.1.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
edition = "2018"

[[bin]]
name = "indradb-wikipedia"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "^1.0.57"
uuid = { version = "0.8.1", features = ["serde"] }
blake2b_simd = "0.5.11"
pbr = "1"
tonic = "0.3.1"
indradb-lib = { path = "indradb/lib" }
indradb-proto = { path = "indradb/proto" }
libc = "0.2.80"
clap = "2"
bzip2 = "0.4.1"
quick-xml = "0.20.0"
regex = "1"
serde = { version = "1", features = ["derive"] }
bincode = "1.3.1"
lazy_static = "1"
tokio = { version = "0.2.23", features = ["net", "macros", "time", "rt-util"]}
warp = "0.2.5"
failure = "0.1.8"
async-channel = "1.5.1"
tera = "1"
